ALTER SESSION SET CONTAINER = FREEPDB1;

-- Create the application user
CREATE USER identity IDENTIFIED BY identity123 QUOTA UNLIMITED ON USERS;

-- Grant privileges
GRANT CONNECT, RESOURCE TO identity;
GRANT CREATE SESSION TO identity;
GRANT CREATE TABLE TO identity;
GRANT CREATE SEQUENCE TO identity;
