<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.personal</groupId>
        <artifactId>token-context</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>token-application</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>com.personal</groupId>
            <artifactId>token-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>com.personal</groupId>
            <artifactId>platform-shared</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>