package com.personal.identity.infrastructure.persistence.mapper;

import com.personal.identity.core.domain.permission.Permission;
import com.personal.identity.core.domain.permission.Role;
import com.personal.identity.core.domain.user.User;
import com.personal.identity.infrastructure.persistence.entity.PermissionEntity;
import com.personal.identity.infrastructure.persistence.entity.RoleEntity;
import com.personal.identity.infrastructure.persistence.entity.UserEntity;
import org.mapstruct.*;

import java.util.Set;

/**
 * MapStruct mapper for {@link User} ⟷ {@link UserEntity}.
 *
 * <p><b>2 sources of permissions:</b>
 * <ul>
 * <li>{@code roles} (via the user_roles table)</li>
 * <li>{@code directPermissions} (via the user_permissions table)</li>
 * </ul>
 *
 * <p>The mapper MUST be invoked within a transaction after the entity has been loaded via
 * {@code @EntityGraph(attributePaths = {"roles", "roles.permissions", "directPermissions"})}.
 * Otherwise, a LazyInitializationException will occur.
 *
 * <h2>Why {@link #toDomain} is manually written (default method)</h2>
 *
 * <p>The {@code User} domain object omits {@code @Builder} and public all-args constructors to
 * encapsulate its state. It can only be instantiated via {@code User.rehydrate(...)}. MapStruct cannot
 * auto-generate this pattern, so {@code toDomain} is a {@code default} method that manually
 * delegates to {@code User.rehydrate}.
 *
 * <p>The two methods {@link #mapRoles} and {@link #mapDirectPermissions} exist so MapStruct can
 * auto-generate their implementations, utilizing {@link RoleMapper} + {@link PermissionMapper} via
 * {@code uses = {...}}.
 *
 * <p><b>passwordHash:</b> mapped bi-directionally. It MUST NEVER appear in the DTO
 * response — ensuring this is the controller layer's responsibility.
 */
@Mapper(uses = {RoleMapper.class, PermissionMapper.class})
public interface UserMapper {

    /**
     * Entity → Domain. Uses {@link User#rehydrate} - bypassing business validation
     * since the state is already guaranteed by the DB (constraints + Flyway migrations).
     */
    default User toDomain(UserEntity entity) {
        if (entity == null) return null;

        return User.rehydrate(
                entity.getId(),
                entity.getUsername(),
                entity.getEmailAddress(),
                entity.getPasswordHash(),
                entity.getFullName(),
                entity.getAccountStatus(),
                mapRoles(entity.getRoles()),
                mapDirectPermissions(entity.getDirectPermissions()),
                entity.getCreatedAt(),
                entity.getUpdatedAt(),
                entity.isDeleted(),
                entity.getDeletedAt()
        );
    }

    /**
     * Auto-generated by MapStruct, using {@link RoleMapper#toDomain(RoleEntity)} for each element.
     * Returns an empty Set if the input is null (following MapStruct conventions).
     */
    Set<Role> mapRoles(Set<RoleEntity> entities);

    /** Similar to {@link #mapRoles}, utilizing {@link PermissionMapper}. */
    Set<Permission> mapDirectPermissions(Set<PermissionEntity> entities);

    /**
     * Domain → Entity, used for CREATE.
     * DOES NOT map audit fields, DOES NOT map deleted/deletedAt - these are
     * managed automatically by JPA/Hibernate.
     */
    @BeanMapping(ignoreByDefault = true, nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "id", source = "id")
    @Mapping(target = "username", source = "username")
    @Mapping(target = "emailAddress", source = "emailAddress")
    @Mapping(target = "passwordHash", source = "passwordHash")
    @Mapping(target = "fullName", source = "fullName")
    @Mapping(target = "accountStatus", source = "accountStatus")
    @Mapping(target = "roles", source = "roles")
    @Mapping(target = "directPermissions", source = "directPermissions")
    UserEntity toEntity(User domain);

    /**
     * Updates an existing entity. DOES NOT update the id (PK remains unchanged).
     *
     * <p><b>Why roles + directPermissions are NOT mapped here:</b> The mapper would REPLACE
     * the entire collection with new entities built from the domain (via RoleMapper/PermissionMapper).
     * These new entities are DETACHED (lacking the @Version from the DB) - when Hibernate auto-flushes,
     * it will throw {@code PropertyValueException: uninitialized version value}.
     * <p>Solution: preserve the managed collection inside {@code @MappingTarget entity}.
     * If a use case requires altering roles, write a dedicated method (e.g., {@code updateRoles})
     * that invokes {@code entity.getRoles().clear()} followed by {@code addAll(reattachedRoles)}.
     * <p>Currently, use cases that modify the user (like change-password) DO NOT alter roles, so omitting
     * them from this mapping is the safest approach.
     */
    @BeanMapping(ignoreByDefault = true, nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "username", source = "username")
    @Mapping(target = "emailAddress", source = "emailAddress")
    @Mapping(target = "passwordHash", source = "passwordHash")
    @Mapping(target = "fullName", source = "fullName")
    @Mapping(target = "accountStatus", source = "accountStatus")
    void updateEntity(User domain, @MappingTarget UserEntity entity);
}