
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.personal</groupId>
        <artifactId>auth-context</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>auth-infrastructure</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <dependency>
            <groupId>com.personal</groupId>
            <artifactId>auth-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.personal</groupId>
            <artifactId>auth-domain</artifactId>
        </dependency>
        <!--
                    platform-shared-jpa: BaseJpaAuditEntity for JPA entities here.
                    This is the ONLY layer that should depend on platform-shared-jpa.
                 -->
        <dependency>
            <groupId>com.personal</groupId>
            <artifactId>platform-shared-jpa</artifactId>
        </dependency>
        <!--  Spring Data JPA  -->
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
        </dependency>
        <!--  Spring Data Redis  -->
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-redis</artifactId>
        </dependency>
        <!--  Spring Security crypto (cho BCryptPasswordEncoder)  -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>
        <!--  MapStruct  -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>