spring:
  application:
    name: identity-service-v5
  datasource:


    #url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-sydney-1.oraclecloud.com))(connect_data=(service_name=g2bd40771e73017_identityservice_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: ADMIN
    password: Pantsirs1@sa22
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-sydney-1.oraclecloud.com))(connect_data=(service_name=g2bd40771e73017_identityservice_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))

  data:
    jpa:
      repositories:
        enabled: true
    redis:
      url: redis://default:jI3oE4Ka94pvZf5nFqRPlGQSIMqEZ60E@redis-14806.c334.asia-southeast2-1.gce.redns.redis-cloud.com:14806
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      password:
        encode-type: argon2
        argon2:
          saltLength: 16
          hashLength: 32
          parallelism: 1
          memory: 4090
          iterations: 3
        bcrypt:
          strength: "10"
      resourceserver:
        jwt:
          jws-algorithms: HS512
          authority-prefix: ROLE_
  batch:
    jdbc:
      isolation-level-for-create: read_committed
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
  snowflake:
    workerId: 1
    datacenterId: 1

logging:
  level:
    root: info
    org.springframework.security: DEBUG
server:
  port: 8084
run-mode: dev
user:
  max-failed-login-attempts: 5
  lockout-time: 600 # in seconds
